#! /bin/sh
### BEGIN INIT INFO
# Provides: kibana 
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: kibana
# Description: This file starts and stops kibana server
# 
### END INIT INFO

KIBANA_DIR=/opt/kibana/
export JAVA_HOME=/opt/java/

FILES=/opt/kibana/config/*.conf
KIBANA_CONFIG_STRING=" "
for f in $FILES
do
  # echo "Processing $f file..."
  # take action on each file. $f store current file name
  KIBANA_CONFIG_STRING="$KIBANA_CONFIG_STRING -f $f"
done
echo $KIBANA_CONFIG_STRING

case "$1" in
 start)
   su kibana -c $KIBANA_DIR/bin/kibana
   #$KIBANA_DIR/bin/kibana $KIBANA_CONFIG_STRING
   ;;
 stop)
   su kibana -c $KIBANA_DIR/bin/kibana
   sleep 10
   ;;
 restart)
   su kibana -c $KIBANA_DIR/bin/kibana
   sleep 20
   su kibana -c $KIBANA_DIR/bin/kibana
   ;;
 *)
   echo "Usage: kibana {start|stop|restart}" >&2
   exit 3
   ;;
esac

#stop_kibanaprocess() {
#	pkill -P 1 -f "kibana
#}

